version: '3.6'
services:
  rabbitmq:
    image: rabbitmq:3.6.6-management
    container_name: rabbitmq
    volumes:
      - rabbit_data:/var/lib/postgresql/rabbitmqdata
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rabbit_data:
